name: Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: ["*"]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: coursier/cache-action@v6
      - uses: actions/setup-java@v2.3.1
        with:
          distribution: temurin
          java-version: 11
          check-latest: true
      - name: Tests
        run: sbt clean test
